### ISSUE TITLE
App is broken when --sources and --target directories are same with --overwrite option is enabled

### ISSUE THREAD

**Issue by baybatu** [yegor256/jpeek#268] opened 2018-07-16 21:26 UTC
App is broken when --sources and --target directories are same when --overwrite option is enabled. It deletes `--sources` directory also.

Example broken command

```
java -jar target/jpeek-jar-with-dependencies.jar --sources /Users/baybatu/workspace/zerocrat/jpeek/jpeek_tests --target /Users/baybatu/workspace/zerocrat/jpeek/jpeek_tests --overwrite
```
Gives following stack trace:

```
Directory /Users/baybatu/workspace/zerocrat/jpeek/jpeek_tests deleted
Exception in thread "main" java.lang.IllegalStateException: java.nio.file.NoSuchFileException: /Users/baybatu/workspace/zerocrat/jpeek/jpeek_tests
	at org.jpeek.skeleton.Classes.iterator(Classes.java:104)
	at org.cactoos.collection.CollectionOf.lambda$new$0(CollectionOf.java:77)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:59)
	at org.cactoos.collection.CollectionEnvelope.iterator(CollectionEnvelope.java:69)
	at org.cactoos.iterable.Mapped.lambda$null$0(Mapped.java:68)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:57)
	at org.cactoos.collection.CollectionOf.lambda$new$0(CollectionOf.java:77)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:59)
	at org.cactoos.collection.CollectionEnvelope.iterator(CollectionEnvelope.java:69)
	at org.cactoos.collection.CollectionEnvelope.iterator(CollectionEnvelope.java:69)
	at org.cactoos.scalar.AndInThreads.value(AndInThreads.java:303)
	at org.cactoos.scalar.AndInThreads.value(AndInThreads.java:66)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:59)
	at org.jpeek.skeleton.Skeleton.packages(Skeleton.java:144)
	at org.jpeek.skeleton.Skeleton.xml(Skeleton.java:107)
	at org.jpeek.App.analyze(App.java:149)
	at org.jpeek.Main.run(Main.java:151)
	at org.jpeek.Main.main(Main.java:115)
Caused by: java.nio.file.NoSuchFileException: /Users/baybatu/workspace/zerocrat/jpeek/jpeek_tests
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
	at java.nio.file.Files.walk(Files.java:3574)
	at java.nio.file.Files.walk(Files.java:3625)
	at org.jpeek.DefaultBase.files(DefaultBase.java:63)
	at org.jpeek.skeleton.Classes.iterator(Classes.java:99)
	... 32 more

Process finished with exit code 1
```

It would be better to validate `--sources` and `--target` before delete `--target` directory and if they are equal, then show user-friendly/descriptive error message.

**Comment by 0crat** [comment] 2018-07-18 06:31
Job [#268](https://github.com/yegor256/jpeek/issues/268) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-07-18 06:33
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @baybatu[/z](https://www.0crat.com/u/baybatu)

**Comment by 0crat** [comment] 2019-04-18 20:48
The job [#268](https://github.com/yegor256/jpeek/issues/268) assigned to @humb1t[/z](https://www.0crat.com/u/humb1t), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/96176eb6-8918-48ab-9872-89cc62896783); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-04-23 21:42
@humb1t[/z](https://www.0crat.com/u/humb1t) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by humb1t** [comment] 2019-04-24 11:18
@0crat wait for #321 approval

**Comment by 0crat** [comment] 2019-04-24 11:19
> @0crat wait for #321 approval ([here](https://github.com/yegor256/jpeek/issues/268#issuecomment-486181107))

@humb1t The impediment for [#268](https://github.com/yegor256/jpeek/issues/268) was registered successfully by @humb1t[/z](https://www.0crat.com/u/humb1t)

**Closed** 2019-06-28 17:13 UTC
Labels: bug, scope, waiting

**Comment by 0crat** [comment] 2019-06-28 17:30
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @baybatu[/z](https://www.0crat.com/u/baybatu) (its creator); I won't close the order; please, re-open it and ask @baybatu[/z](https://www.0crat.com/u/baybatu) to close it

**Comment by 0crat** [comment] 2019-07-05 09:56
The job [#268](https://github.com/yegor256/jpeek/issues/268) is now out of scope

**Comment by 0crat** [comment] 2019-07-05 09:56
@humb1t[/z](https://www.0crat.com/u/humb1t) resigned from [#268](https://github.com/yegor256/jpeek/issues/268), since the job is not in scope anymore
