### ISSUE TITLE
Update jcabi-parent to 1.0-SNAPSHOT (solves xcop issue)

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/jpeek#313] opened 2019-01-28 16:55 UTC
Let's update to new jcabi version (1.0-SNAPSHOT) because this new version solves xcop issue on windows.

**Comment by paulodamaso** [comment] 2019-03-30 04:33
@0crat in

**Comment by 0crat** [comment] 2019-03-30 04:41
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/313#issuecomment-478206268))

@paulodamaso Job [#313](https://github.com/yegor256/jpeek/issues/313) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-03-30 04:48
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by mohamednizar** [comment] 2019-11-12 05:33
@0crat status

**Comment by 0crat** [comment] 2019-11-12 05:39
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/313#issuecomment-552741519))

@mohamednizar This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#313](https://github.com/yegor256/jpeek/issues/313) is [in scope](http://www.zerocracy.com/policy.html#14) for 8mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23313%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment] 2019-11-12 17:09
The job [#313](https://github.com/yegor256/jpeek/issues/313) assigned to @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/52e357b8-9fcf-46ff-8ae1-7970de1c5532); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by stepanov-dmitry** [comment] 2019-11-12 17:21
@0crat wait please

**Comment by 0crat** [comment] 2019-11-12 17:22
> @0crat wait please ([here](https://github.com/yegor256/jpeek/issues/313#issuecomment-552996683))

@stepanov-dmitry The impediment for [#313](https://github.com/yegor256/jpeek/issues/313) was registered successfully by @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry)

**Comment by paulodamaso** [comment] 2020-03-18 02:50
@0crat assign me

**Comment by 0crat** [comment] 2020-03-18 07:03
> @0crat assign me ([here](https://github.com/yegor256/jpeek/issues/313#issuecomment-600397519))

@paulodamaso The job [#313](https://github.com/yegor256/jpeek/issues/313) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/f5ee95f6-6052-45b4-8983-62681f092653); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2020-03-25 16:30
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2020-03-30 03:07
The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#313](https://github.com/yegor256/jpeek/issues/313), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2020-03-30 16:05
The job [#313](https://github.com/yegor256/jpeek/issues/313) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/78bb4af7-153f-4746-8b02-4f9d13dda045); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2020-03-30 16:07
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@aa9bbd637b9c, thread: PQ-C7JGJ00DP
com.zerocracy.farm.sync.SyncItem[101] java.lang.IllegalStateException: Failed to acquire a lock java.util.concurrent.locks.ReentrantReadWriteLock@2fc95c08[Write locks = 1, Read locks = 0]/java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock@306a5dab[Locked by thread BkParallel-2] for "2017/10/C7JGJ00DP/estimates.xml" in 15s
```

[0.52.9](https://github.com/zerocracy/farm): CID: [427c6cbc-3c74-40e0-8909-aa1cf329357c](https://www.0crat.com/footprint/C7JGJ00DP/427c6cbc-3c74-40e0-8909-aa1cf329357c), Type: "Start order"

**Comment by victornoel** [comment] 2020-03-30 16:30
@0crat wait for #434 to be merged

**Comment by victornoel** [comment] 2020-04-01 08:55
@fabriciofx the PR has been merged, I believe it fixes your problem, can you close this issue?

**Comment by victornoel** [comment] 2020-04-02 09:07
@paulodamaso I'm not sure @fabriciofx is around here anymore, the issue is more than a year old, can you close it please?

**Comment by paulodamaso** [comment] 2020-04-02 11:19
@victornoel For sure, thank you

**Closed by paulodamaso** 2020-04-02 11:19 UTC
Labels: scope, waiting

**Comment by 0crat** [comment] 2020-04-02 11:53
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment] 2020-04-02 12:28
@0crat quality good

**Comment by paulodamaso** [comment] 2020-04-05 03:28
@rultor release tag is `0.30.18`
