### ISSUE TITLE
Build of whole project is broken.

### ISSUE THREAD

**Issue by humb1t** [yegor256/jpeek#320] opened 2019-04-19 18:17 UTC
Using command from README.md:
```
mvn clean install -Pqulice
```

I tried to build repo on my local machine (Windows 10) and it failed with:
```
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.8:check (jacoco-check) @ jpeek ---
[INFO] Loading execution data file C:\Users\Nikita_Puzankov\workspace\personal\jpeek\target\jacoco.exec
[INFO] Analyzed bundle 'jpeek' with 35 classes
[WARNING] Rule violated for bundle jpeek: lines covered ratio is 0.65, but expected minimum is 0.67
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:58 min
[INFO] Finished at: 2019-04-19T22:13:29+04:00
[INFO] Final Memory: 33M/329M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.7.8:check (jacoco-check) on project jpeek: Coverage checks have not been met. See log for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
**Without any local changes.**

I would like to see working build to work on the project instead of covering code with tests for free :-)

**Comment by 0crat** [comment] 2019-04-19 18:17
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment] 2019-04-19 20:32
@humb1t Strange, it shouldn't allow to merge the code with coverage problems. Anyways, let's fix it

**Comment by paulodamaso** [comment] 2019-04-19 20:32
@0crat in

**Comment by 0crat** [comment] 2019-04-19 20:33
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/320#issuecomment-485007128))

@paulodamaso Job [#320](https://github.com/yegor256/jpeek/issues/320) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-04-19 20:39
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @humb1t[/z](https://www.0crat.com/u/humb1t)

**Comment by humb1t** [comment] 2019-04-21 14:21
@0crat status

**Comment by 0crat** [comment] 2019-04-21 14:22
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/320#issuecomment-485255610))

@humb1t This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#320](https://github.com/yegor256/jpeek/issues/320) is [in scope](http://www.zerocracy.com/policy.html#14) for 2days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @humb1t[/z](https://www.0crat.com/u/humb1t): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23320%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment] 2019-04-21 21:45
@0crat assign @humb1t

**Comment by 0crat** [comment] 2019-04-21 21:47
> @0crat assign @humb1t  ([here](https://github.com/yegor256/jpeek/issues/320#issuecomment-485284527))

@paulodamaso The job [#320](https://github.com/yegor256/jpeek/issues/320) assigned to @humb1t[/z](https://www.0crat.com/u/humb1t), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/9fdcb400-35ab-40d2-9b0d-3cb2b49fe07f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-04-21 21:47
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment] 2019-04-21 21:47
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment] 2019-04-26 22:40
@humb1t[/z](https://www.0crat.com/u/humb1t) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2019-05-01 21:58
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @humb1t[/z](https://www.0crat.com/u/humb1t)

**Comment by 0crat** [comment] 2019-05-01 21:58
The user @humb1t[/z](https://www.0crat.com/u/humb1t) resigned from [#320](https://github.com/yegor256/jpeek/issues/320), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by paulodamaso** [comment] 2019-05-01 22:33
@0crat assign @humb1t

**Comment by paulodamaso** [comment] 2019-05-01 22:34
@humb1t Please set the issue in waiting while your PR is being merged. This way @0crat does not takes it from you while someones review your PR

**Comment by 0crat** [comment] 2019-05-01 22:34
Are you speaking to me or about me [here](https://github.com/yegor256/jpeek/issues/320#issuecomment-488464792); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment] 2019-05-01 22:34
> @0crat assign @humb1t  ([here](https://github.com/yegor256/jpeek/issues/320#issuecomment-488464358))

@paulodamaso The job [#320](https://github.com/yegor256/jpeek/issues/320) assigned to @humb1t[/z](https://www.0crat.com/u/humb1t), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/4e2b3551-9e29-4ccb-aaf7-d23dbb5e0c64); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-05-01 22:35
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment] 2019-05-01 22:35
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by humb1t** [comment] 2019-05-02 05:54
@0crat wait #321

**Comment by 0crat** [comment] 2019-05-02 05:54
> @0crat wait #321  ([here](https://github.com/yegor256/jpeek/issues/320#issuecomment-488560292))

@humb1t The impediment for [#320](https://github.com/yegor256/jpeek/issues/320) was registered successfully by @humb1t[/z](https://www.0crat.com/u/humb1t)

**Comment by 0crat** [comment] 2019-06-28 17:30
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @humb1t[/z](https://www.0crat.com/u/humb1t) (its creator); I won't close the order; please, re-open it and ask @humb1t[/z](https://www.0crat.com/u/humb1t) to close it

**Comment by humb1t** [comment] 2019-06-30 11:59
@paulodamaso reopen please and I will close the issue ^^

**Comment by 0crat** [comment] 2019-07-04 04:14
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by aivinog1** [comment] 2019-07-16 03:21
@humb1t @paulodamaso have reopened this issue. Can you close it?

**Closed** 2019-07-16 09:18 UTC
Labels: scope, waiting

**Comment by 0crat** [comment] 2019-07-16 09:50
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @humb1t[/z](https://www.0crat.com/u/humb1t), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2019-07-16 09:54
The job [#320](https://github.com/yegor256/jpeek/issues/320) is now out of scope

**Comment by fabriciofx** [comment] 2019-07-16 13:05
@0crat quality good

**Comment by 0crat** [comment] 2019-07-16 13:09
Quality review completed: +4 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment] 2019-07-16 13:09
Order was finished, quality is "good": +35 point(s) just awarded to @humb1t[/z](https://www.0crat.com/u/humb1t)
