### ISSUE TITLE
All numeric tests are broken in MetricsTest.java - Internationalization problem

### ISSUE THREAD

**Issue by oridan** [yegor256/jpeek#246] opened 2018-05-24 21:46 UTC
When executing MetricsTest.java on issue #147, the only tests that passed were those that uses Double.NaN as value. All others tests that uses numeric values failed.
I made a PR anyway and they... passed.

On the stacktrace (at the bottom) is this:
> Caused by: javax.xml.transform.TransformerException: Expected ], mas found: ,

So, all error where gone when I inserted on the testTarget():` Locale.setDefault(Locale.UK);`

As this project have contributors spreed around the world, I sugest that it sets the default locale as UK. This way will not be necessary to add ` Locale.setDefault(Locale.UK);` to every single test.

This was the stacktrace I was getting:
> java.lang.IllegalArgumentException: invalid XPath query '//class[@id='Bar' and number(@value)=6,0000]' by com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl
	at com.jcabi.xml.XMLDocument.nodes(XMLDocument.java:397)
	at com.jcabi.matchers.XPathMatcher.matchesSafely(XPathMatcher.java:76)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at com.jcabi.matchers.AllOfThatPrintsOnlyWrongMatchers.matches(AllOfThatPrintsOnlyWrongMatchers.java:81)
	at org.hamcrest.DiagnosingMatcher.matches(DiagnosingMatcher.java:12)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.jpeek.MetricsTest.testsTarget(MetricsTest.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: Expected ], mas found: ,
	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:285)
	at com.jcabi.xml.XMLDocument.fetch(XMLDocument.java:466)
	at com.jcabi.xml.XMLDocument.nodes(XMLDocument.java:385)
	... 38 more
Caused by: javax.xml.transform.TransformerException: Expected ], mas found: ,
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.error(XPathParser.java:612)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.consumeExpected(XPathParser.java:530)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.Predicate(XPathParser.java:1939)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.Step(XPathParser.java:1728)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelativeLocationPath(XPathParser.java:1628)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.LocationPath(XPathParser.java:1599)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(XPathParser.java:1319)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(XPathParser.java:1238)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(XPathParser.java:1144)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(XPathParser.java:1065)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(XPathParser.java:1007)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(XPathParser.java:932)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(XPathParser.java:872)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:836)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(XPathParser.java:809)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(XPathParser.java:792)
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.initXPath(XPathParser.java:131)
	at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:180)
	at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:268)
	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.eval(XPathImpl.java:189)
	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:271)
	... 40 more

**Comment by 0crat** [comment] 2018-05-24 21:46
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by paulodamaso** [comment] 2019-01-15 21:22
@0crat in

**Comment by 0crat** [comment] 2019-01-15 21:38
> @0crat in ([here](https://github.com/yegor256/jpeek/issues/246#issuecomment-454556294))

@paulodamaso Job [#246](https://github.com/yegor256/jpeek/issues/246) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-01-15 21:56
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by 0crat** [comment] 2019-07-26 20:30
The job [#246](https://github.com/yegor256/jpeek/issues/246) assigned to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/dfcece25-1a72-40fd-9afb-f79789221e63); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2019-08-05 18:44
@rajanamistry[/z](https://www.0crat.com/u/rajanamistry) this job was assigned to you 10days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2019-08-05 20:45
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @rajanamistry[/z](https://www.0crat.com/u/rajanamistry)

**Comment by 0crat** [comment] 2019-08-05 20:45
The user @rajanamistry[/z](https://www.0crat.com/u/rajanamistry) resigned from [#246](https://github.com/yegor256/jpeek/issues/246), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2019-08-15 20:13
The job [#246](https://github.com/yegor256/jpeek/issues/246) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/f780a0c8-2b1b-4aad-81df-33288e61c99c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2019-08-25 20:18
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment] 2019-08-25 20:18
The user @uurl[/z](https://www.0crat.com/u/uurl) resigned from [#246](https://github.com/yegor256/jpeek/issues/246), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2019-08-25 20:33
The job [#246](https://github.com/yegor256/jpeek/issues/246) assigned to @dfrau32[/z](https://www.0crat.com/u/dfrau32), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/12adb33b-8d27-47f7-892f-3094b2199489); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2019-09-04 19:40
@dfrau32[/z](https://www.0crat.com/u/dfrau32) this job was assigned to you 10days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by dgarus** [comment] 2020-02-14 11:24
@0crat status

**Comment by 0crat** [comment] 2020-02-14 11:46
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/246#issuecomment-586219428))

@dgarus This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#246](https://github.com/yegor256/jpeek/issues/246) is [in scope](http://www.zerocracy.com/policy.html#14) for 13mon
  * The role is `DEV`
  * The job is assigned to @dgarus[/z](https://www.0crat.com/u/dgarus) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @oridan[/z](https://www.0crat.com/u/oridan): This user reported the ticket
    * @rajanamistry[/z](https://www.0crat.com/u/rajanamistry): User was resigned from the ticket
    * @uurl[/z](https://www.0crat.com/u/uurl): User was resigned from the ticket
    * @dfrau32[/z](https://www.0crat.com/u/dfrau32): User was resigned from the ticket
    * @romach[/z](https://www.0crat.com/u/romach): User was resigned from the ticket
    * @thomas-melville[/z](https://www.0crat.com/u/thomas-melville): User was resigned from the ticket
    * @baybatu[/z](https://www.0crat.com/u/baybatu): User was resigned from the ticket
    * @mohamednizar[/z](https://www.0crat.com/u/mohamednizar): User was resigned from the ticket
    * @ebercamargo[/z](https://www.0crat.com/u/ebercamargo): User was resigned from the ticket
    * @englishman[/z](https://www.0crat.com/u/englishman): User was resigned from the ticket
    * @akryvtsun[/z](https://www.0crat.com/u/akryvtsun): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23246%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by dgarus** [comment] 2020-02-14 12:21
@oridan Hi! 
I'm trying to reproduce the problem with Internationalization.
Could you please clarify what Internationalization should be to get the problem?

**Comment by dgarus** [comment] 2020-02-16 11:10
@0crat wait

**Comment by 0crat** [comment] 2020-02-16 11:25
> @0crat wait ([here](https://github.com/yegor256/jpeek/issues/246#issuecomment-586693748))

@dgarus The impediment for [#246](https://github.com/yegor256/jpeek/issues/246) was registered successfully by @dgarus[/z](https://www.0crat.com/u/dgarus)

**Comment by paulodamaso** [comment] 2020-02-18 12:40
@dgarus Hey, I think that the problem happened using ISO-8859-1 locale (latin 1)

**Comment by dgarus** [comment] 2020-02-18 15:45
@paulodamaso 
This issue was already fixed.
https://github.com/yegor256/jpeek/pull/262

**Comment by dgarus** [comment] 2020-02-19 10:16
@paulodamaso
Let's clarify the task requirements.
As I understand the problem was to get rid adding 
`Locale.setDefault(Locale.UK);` in every single test of class.

The way from #262 does not require to change the default locale at all, and I think it is the best solution.

Should we change the current solution and set the default locale ones per class?

**Comment by paulodamaso** [comment] 2020-02-19 13:49
@dgarus I think that we should try to configure this locale outside our code

**Comment by dgarus** [comment] 2020-02-19 19:53
@paulodamaso

**Comment by dgarus** [comment] 2020-02-20 07:55
@paulodamaso 
The way that we are planning to use has a drawback - to run the test in IDE, you should set up VM options. That is inconvenient, so I think the current approach is better.

**Comment by paulodamaso** [comment] 2020-02-20 12:16
@dgarus Well, let's leave this the way it is. Just put a comment in the method doc to document the issue

**Comment by dgarus** [comment] 2020-02-20 12:27
@paulodamaso sorry, it sounds ambiguous for me.
We set up the default locale in pom file and document the test class with "to run the test you should set up VM options". Ok?

**Comment by paulodamaso** [comment] 2020-02-20 12:29
@dgarus Sorry for the bad wording. I have a doubt here, even if we set up the locale on `pom.xml` we still have to execute it using VM args?

**Comment by dgarus** [comment] 2020-02-20 12:35
@paulodamaso If you run the test through maven, they will be ok.
But if you want to run the test from IDE, you should set up VM options like in the pom file.

**Comment by paulodamaso** [comment] 2020-02-20 17:38
@dgarus Which IDE are you using? I don't have the problem using IntelliJ IDEA

**Comment by dgarus** [comment] 2020-02-21 05:50
@paulodamaso
I suspect EN is default locale on your comp.

**Comment by paulodamaso** [comment] 2020-02-21 11:35
@dgarus Please take a look, I'm using brazilian locales:
![image](https://user-images.githubusercontent.com/33915433/75031442-ffaa7980-5484-11ea-9f21-661d52b886ac.png)
Anyway, we already spent too much on this issue. Please implement the solution you proposed in https://github.com/yegor256/jpeek/issues/246#issuecomment-588996663

**Comment by dgarus** [comment] 2020-02-21 12:16
@paulodamaso ok, done.

**Comment by dgarus** [comment] 2020-02-26 15:19
@oridan could you please close the issue?

**Comment by paulodamaso** [comment] 2020-02-27 11:34
@dgarus Thank you!

**Closed by paulodamaso** 2020-02-27 11:34 UTC
Labels: scope, waiting

**Comment by 0crat** [comment] 2020-02-27 11:59
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @dgarus[/z](https://www.0crat.com/u/dgarus), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment] 2020-02-27 12:04
@0crat quality good

**Comment by 0crat** [comment] 2020-02-27 12:13
Order was finished, quality is "good": +35 point(s) just awarded to @dgarus[/z](https://www.0crat.com/u/dgarus)

**Comment by 0crat** [comment] 2020-02-27 12:15
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
