### ISSUE TITLE
Use Appveyor as CI too

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/jpeek#302] opened 2019-01-18 01:47 UTC
Let's use Appveyor as CI too, not only Travis. Some erros are detected only Windows OSes.

**Comment by 0crat** [comment] 2019-01-18 01:47
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment] 2019-01-18 03:22
@0crat in

**Comment by 0crat** [comment] 2019-01-18 03:31
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment] 2019-10-03 18:16
The job [#302](https://github.com/yegor256/jpeek/issues/302) assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/2cf6a26e-bbe6-43dc-a4a1-e27e682cc93d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by mohamednizar** [comment] 2019-10-04 10:35
@fabriciofx , do we need appveyor only for Windows or both Linux & Windows ?

**Comment by fabriciofx** [comment] 2019-10-04 14:46
@mohamednizar just for Windows. To Linux we use Travis CI.

**Comment by mohamednizar** [comment] 2019-10-04 14:48
@fabriciofx , I have created a pull request, please review it, refer #345

**Comment by mohamednizar** [comment] 2019-10-07 11:29
@0crat status

**Comment by 0crat** [comment] 2019-10-07 11:44
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/302#issuecomment-538963587))

@mohamednizar This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#302](https://github.com/yegor256/jpeek/issues/302) is [in scope](http://www.zerocracy.com/policy.html#14) for 9mon
  * The role is `DEV`
  * The job is assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) for [4days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23302%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment] 2019-10-08 18:44
@mohamednizar[/z](https://www.0crat.com/u/mohamednizar) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2019-10-13 20:13
The user @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) resigned from [#302](https://github.com/yegor256/jpeek/issues/302), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2019-10-13 20:14
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by mohamednizar** [comment] 2019-10-14 04:10
@paulodamaso , why this task is reassigned, even after I committed the code ? what  going on ?

**Comment by paulodamaso** [comment] 2019-10-18 15:59
@mohamednizar The code was merged, but @0crat just pays the issue performer when the issue is closed, as per [§7](http://www.zerocracy.com/policy.html#7). @0crat doesn't have to know when the issue is solved, so you have to manually inform the issue reporter to close each issue after merge.

Also, as stated in [§42](http://www.zerocracy.com/policy.html#42), a link to the original link must be added into the description of the PR, making it easier to find which issue originated which PR and vice versa.

Last,  I suggest you to put issues on hold (@0crat `wait` command) as soon as you make a PR. Sometimes the reviewer takes too long to review it, or the architect to merge it, and putting it on hold prevents that the bot removes that issues from you.

**Comment by 0crat** [comment] 2019-10-18 15:59
Are you speaking to me or about me [here](https://github.com/yegor256/jpeek/issues/302#issuecomment-543810209); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by mohamednizar** [comment] 2019-10-26 17:37
@0crat wait

**Comment by 0crat** [comment] 2019-10-26 18:06
> @0crat wait ([here](https://github.com/yegor256/jpeek/issues/302#issuecomment-546623980))

@mohamednizar Job `gh:yegor256/jpeek#302` is not assigned, can't get performer

**Comment by mohamednizar** [comment] 2019-10-30 01:58
@paulodamaso will Zerocrat give reputation soon after the closing this ticket? Will it revise the negative points I was awarded for this job?

**Comment by paulodamaso** [comment] 2019-10-30 16:48
@0crat status

**Comment by paulodamaso** [comment] 2019-10-30 18:18
@mohamednizar I assigned it to you, and will close it as soon as @0crat register the assignement. Let's see how it will behave

**Comment by 0crat** [comment] 2019-10-30 18:18
Are you speaking to me or about me [here](https://github.com/yegor256/jpeek/issues/302#issuecomment-548047096); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment] 2019-10-30 18:25
> @0crat assign @mohamednizar  ([here](https://github.com/yegor256/jpeek/issues/302#issuecomment-548046699))

@paulodamaso The job [#302](https://github.com/yegor256/jpeek/issues/302) assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/f0c66109-54cc-4972-b770-c03a03aba105); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-10-30 18:25
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Closed** 2019-10-30 18:36 UTC
Labels: scope

**Comment by 0crat** [comment] 2019-10-30 18:55
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment] 2019-10-30 18:56
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 12@b7e726625068, thread: PQ-C7JGJ00DP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/jpeek#302] declared for identity constraint of element "speed".
```

[0.50.34](https://github.com/zerocracy/farm): CID: [cc81d0de-6aba-4477-9bdb-b0164bb59cc4](https://www.0crat.com/footprint/C7JGJ00DP/cc81d0de-6aba-4477-9bdb-b0164bb59cc4), Type: "Order was finished"

**Comment by 0crat** [comment] 2019-10-30 18:56
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) please review this job completed by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2019-10-30 18:56
The job [#302](https://github.com/yegor256/jpeek/issues/302) is now out of scope

**Comment by paulodamaso** [comment] 2019-10-30 19:28
@0crat quality good

**Comment by 0crat** [comment] 2019-10-30 19:35
Order was finished, quality is "good": +40 point(s) just awarded to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by 0crat** [comment] 2019-10-30 19:50
Quality review completed: +4 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
