### ISSUE TITLE
MetricsTest.java:38-40: NHD needs to be tested against...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#121] opened 2018-01-28 16:47 UTC
The puzzle `93-25a7c267` from #93 has to be resolved:

https://github.com/yegor256/jpeek/blob/723c1a0e31123a9efe6a58f94408a52313ee6ee3/src/test/java/org/jpeek/MetricsTest.java#L38-L40

The puzzle was created by George Aristy on 26-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment] 2018-01-28 16:48
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: BkParallel-3 interrupted while waiting for "roles.xml" in C7JGJ00DP for 55s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:121)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2018-01-28 19:52
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: BkParallel-5 interrupted while waiting for "roles.xml" in C7JGJ00DP for 56s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:121)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2018-01-28 20:53
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: BkParallel-8 interrupted while waiting for "roles.xml" in C7JGJ00DP for 55s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:121)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2018-01-28 21:55
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: BkParallel-7 interrupted while waiting for "roles.xml" in C7JGJ00DP for 55s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:121)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2018-01-28 22:23
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: BkParallel-4 interrupted while waiting for "claims.xml" in C7JGJ00DP for 56s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:121)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2018-01-28 22:56
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: BkParallel-0 interrupted while waiting for "roles.xml" in C7JGJ00DP for 55s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:121)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2018-01-28 23:58
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: BkParallel-9 interrupted while waiting for "roles.xml" in C7JGJ00DP for 56s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:121)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2018-01-29 00:58
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: BkParallel-7 interrupted while waiting for "roles.xml" in C7JGJ00DP for 55s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:121)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2018-01-29 03:01
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: BkParallel-7 interrupted while waiting for "roles.xml" in C7JGJ00DP for 55s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:121)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2018-01-29 04:02
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
java.lang.IllegalStateException: BkParallel-6 interrupted while waiting for "roles.xml" in C7JGJ00DP for 55s
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:88)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:121)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0pdd** [comment] 2018-02-22 17:51
@0pdd all puzzles are solved

**Comment by 0pdd** [comment] 2018-02-23 06:46
@0pdd all puzzles are solved

**Comment by 0pdd** [comment] 2018-02-23 07:23
@0pdd all puzzles are solved

**Comment by paulodamaso** [comment] 2018-12-17 11:55
@0crat assign @Serranya

**Comment by 0crat** [comment] 2018-12-17 12:02
> @0crat assign @Serranya  ([here](https://github.com/yegor256/jpeek/issues/121#issuecomment-447819607))

@paulodamaso The job [#121](https://github.com/yegor256/jpeek/issues/121) assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1b709366-9f3d-4f99-a687-19983d1fca4b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2018-12-17 12:10
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by Serranya** [comment] 2018-12-23 09:52
@0crat wait #284

**Comment by 0crat** [comment] 2018-12-23 10:05
> @0crat wait for #284  ([here](https://github.com/yegor256/jpeek/issues/121#issuecomment-449625625))

@Serranya The impediment for [#121](https://github.com/yegor256/jpeek/issues/121) was registered successfully by @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by Serranya** [comment] 2018-12-23 13:45
For documentation purposes:

in the PR [I wrote](https://github.com/yegor256/jpeek/pull/284) that we either calculate the metric wrong, or the Puzzle is wrong.

After consulting with `ARC` we decided that the metric is correct but the puzzle wrong. Therefore the PR is a little bit different that described in the puzzle.

**Comment by 0crat** [comment] 2018-12-24 17:45
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @0pdd[/z](https://www.0crat.com/u/0pdd) (its creator); I won't close the order; please, re-open it and ask @0pdd[/z](https://www.0crat.com/u/0pdd) to close it

**Comment by Serranya** [comment] 2018-12-24 18:12
@paulodamaso seems like something is wrong here. @0crat did not award me any points.

**Comment by 0crat** [comment] 2018-12-24 18:12
Are you speaking to me or about me [here](https://github.com/yegor256/jpeek/issues/121#issuecomment-449760747); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment] 2018-12-24 18:30
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment] 2018-12-24 18:31
@0crat boost 4x

**Comment by 0crat** [comment] 2018-12-24 18:31
> @0crat boost 4x ([here](https://github.com/yegor256/jpeek/issues/121#issuecomment-449761969))

@paulodamaso Boost 4x was set for [#121](https://github.com/yegor256/jpeek/issues/121)

**Comment by 0crat** [comment] 2018-12-24 18:32
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment] 2018-12-24 18:32
@0crat status

**Comment by 0crat** [comment] 2018-12-24 18:33
> @0crat status ([here](https://github.com/yegor256/jpeek/issues/121#issuecomment-449762035))

@paulodamaso This is what I know about this job in [C7JGJ00DP](https://www.0crat.com/p/C7JGJ00DP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#121](https://github.com/yegor256/jpeek/issues/121) is [in scope](http://www.zerocracy.com/policy.html#14) for 7days
  * The role is `DEV`
  * The job is assigned to @serranya[/z](https://www.0crat.com/u/serranya) for [7days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 60 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7JGJ00DP?q=%7Bjob%3A%27gh%3Ayegor256%2Fjpeek%23121%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Closed** 2018-12-24 18:34 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2018-12-24 18:51
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ddb7c286-aac3-4cec-a089-28737bc1c2bb, thread: AsyncProc-6
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/jpeek#121] declared for identity constraint of element "verbosity".
```

[0.39.7](https://github.com/zerocracy/farm): CID: [ce0de0e0-6af5-4353-94c0-58e4558d3cbc](https://www.0crat.com/footprint/C7JGJ00DP/ce0de0e0-6af5-4353-94c0-58e4558d3cbc), Type: "Close job"

**Comment by 0crat** [comment] 2018-12-24 18:51
@cucumber007[/z](https://www.0crat.com/u/cucumber007) please review this job completed by @serranya[/z](https://www.0crat.com/u/serranya), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2018-12-24 18:52
The job [#121](https://github.com/yegor256/jpeek/issues/121) is now out of scope

**Comment by cucumber007** [comment] 2019-01-13 18:40
@0crat quality good

**Comment by 0crat** [comment] 2019-01-13 18:55
Quality review completed: +8 point(s) just awarded to @cucumber007[/z](https://www.0crat.com/u/cucumber007)
