### ISSUE TITLE
LCOM4.xsl:55-57: LCOM4: #156 needs to be fixed in order...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#215] opened 2018-02-26 09:40 UTC
The puzzle `8-429ff082` from #8 has to be resolved:

https://github.com/yegor256/jpeek/blob/26b20a9501bca68cd1a9b99fbceec3e485dfd22e/src/main/resources/org/jpeek/metrics/LCOM4.xsl#L55-L57

The puzzle was created by rultor on 26-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment] 2018-02-26 09:42
Job [#215](https://github.com/yegor256/jpeek/issues/215) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-11-29 07:38
The job [#215](https://github.com/yegor256/jpeek/issues/215) assigned to @mesut[/z](https://www.0crat.com/u/mesut), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/e70e9388-545b-4f14-8f23-2ee146917740); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2018-12-09 07:48
The user @mesut[/z](https://www.0crat.com/u/mesut) resigned from [#215](https://github.com/yegor256/jpeek/issues/215), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2018-12-09 07:48
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @mesut[/z](https://www.0crat.com/u/mesut)

**Comment by 0pdd** [comment] 2019-01-25 18:36
@0pdd the puzzle [#310](https://github.com/yegor256/jpeek/issues/310) is still not solved.

**Closed** 2019-01-25 18:36 UTC
Labels: bug, pdd, scope

**Comment by 0crat** [comment] 2019-01-25 18:54
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @0pdd[/z](https://www.0crat.com/u/0pdd) (its creator); I won't close the order; please, re-open it and ask @0pdd[/z](https://www.0crat.com/u/0pdd) to close it

**Comment by 0crat** [comment] 2019-01-31 10:40
@cucumber007[/z](https://www.0crat.com/u/cucumber007) please review this job completed by @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2019-01-31 10:41
The job [#215](https://github.com/yegor256/jpeek/issues/215) is now out of scope

**Comment by 0pdd** [comment] 2020-03-09 13:54
@0pdd the puzzle [#415](https://github.com/yegor256/jpeek/issues/415) is still not solved; solved: [#310](https://github.com/yegor256/jpeek/issues/310).

**Comment by 0pdd** [comment] 2020-03-21 03:32
@0pdd the puzzle [#431](https://github.com/yegor256/jpeek/issues/431) is still not solved; solved: [#310](https://github.com/yegor256/jpeek/issues/310), [#415](https://github.com/yegor256/jpeek/issues/415).
